### PR TITLE
Add Steam Deck built-in controller support

### PR DESCRIPTION
**Pull request by coolbho3k**
This PR adds support for the Steam Deck's built-in controller.

It seems to be as simple as adding the correct VID and PID.

Video showing it in action: https://www.youtube.com/watch?v=KCYmJfSWhtw

### CODE REVIEW

**Comment by Roboron3042** [comment]
Fantastic! Please add somewhere in the README (ideally at the start) that this works for Steam Deck too 🙂

Maybe we should choose another name...

**Comment by coolbho3k** [comment]
Will do!

**Comment by coolbho3k** [comment]
Done!

**Comment by Roboron3042** [comment]
Thank you!

**Pull request merged**
